In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import seaborn as sns

In [3]:
data = pd.read_excel(r'/content/drive/MyDrive/Dataset/growth_assignment_data.xlsx')
df = pd.DataFrame(data)

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [4]:
print(df.shape)
print(df.head(15))

(3210, 5)
         Date  # of Orders Status of Order    Total CBV Service
0  2016-01-01        180.0       Cancelled   76076000.0  GO-BOX
1  2016-01-02        210.0       Cancelled   92423695.0  GO-BOX
2  2016-01-03        230.0       Cancelled  104029380.0  GO-BOX
3  2016-01-04        250.0       Cancelled  107114280.0  GO-BOX
4  2016-01-05        210.0       Cancelled   90296570.0  GO-BOX
5  2016-01-06        190.0       Cancelled   74894820.0  GO-BOX
6  2016-01-07        200.0       Cancelled   83905185.0  GO-BOX
7  2016-01-08        300.0       Cancelled  123198530.0  GO-BOX
8  2016-01-09        320.0       Cancelled  142122890.0  GO-BOX
9  2016-01-10        250.0       Cancelled  108576650.0  GO-BOX
10 2016-01-11        280.0       Cancelled  143598000.0  GO-BOX
11 2016-01-12        320.0       Cancelled  152468225.0  GO-BOX
12 2016-01-13        290.0       Cancelled  135244655.0  GO-BOX
13 2016-01-14        330.0       Cancelled  172153800.0  GO-BOX
14 2016-01-15        270.0       Cancelled  143052455.0  GO-BOX

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3210 entries, 0 to 3209
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             3210 non-null   datetime64[ns]
 1   # of Orders      3210 non-null   float64
 2   Status of Order  3210 non-null   object
 3   Total CBV        3210 non-null   float64
 4   Service          3210 non-null   object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 125.5+ KB

In [6]:
df.columns = df.columns.str.strip()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3210 entries, 0 to 3209
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             3210 non-null   datetime64[ns]
 1   # of Orders      3210 non-null   float64
 2   Status of Order  3210 non-null   object
 3   Total CBV        3210 non-null   float64
 4   Service          3210 non-null   object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 125.5+ KB

In [8]:
df1 = df.rename({'Date' : 'date', '# of Orders' : 'num_of_order', 'Status of Order' : 'status', 'Total CBV' : 'total_cbv', 'Service' : 'service'},axis=1)

In [9]:
df1['month']=pd.DatetimeIndex(df1['date']).month
df1.head()

        date  num_of_order     status    total_cbv service  month
0 2016-01-01         180.0  Cancelled   76076000.0  GO-BOX      1
1 2016-01-02         210.0  Cancelled   92423695.0  GO-BOX      1
2 2016-01-03         230.0  Cancelled  104029380.0  GO-BOX      1
3 2016-01-04         250.0  Cancelled  107114280.0  GO-BOX      1
4 2016-01-05         210.0  Cancelled   90296570.0  GO-BOX      1

In [10]:
pivot = df1.pivot_table(index=['service','status'],values=['num_of_order'],columns=['month'],aggfunc='sum',fill_value = 0,margins=True,margins_name = 'grand_total')

In [11]:
pivot

                            num_of_order                              \
month                                  1         2         3       4
service     status
GO-BOX      Cancelled               8710      8920     11910     430
            Completed              19310     19390     25060    1270
            No Driver Found         1200      1020      1230      60
            Other                      0         0         0       0
GO-CLEAN    Cancelled                420       510       770      40
            Completed               4190      3930      6160     230
            No Driver Found           80       150       370      10
            Other                     20       470       180       0
GO-FOOD     Cancelled            1032510    542270    443540   15610
            Completed            2328700   2068690   2242370   75240
            No Driver Found        15610     13200     10210     240
            Other                   1490        40       140       0
GO-GLAM     Cancelled                290       460       490      30
            Completed               1920      2320      3260     130
            No Driver Found          560       740       740      20
            Other                     10        10        20       0
GO-KILAT    Cancelled                100       290       620      40
            Completed               1630      5160      9980     570
            No Driver Found           30       130      1110     110
            Other                      0         0         0       0
GO-MART     Cancelled              45810     22310     16980     600
            Completed              72140     59960     62230    2100
            No Driver Found           20        90       280      20
            Other                      0         0         0       0
GO-MASSAGE  Cancelled               1800      2070      3290     170
            Completed              12250     12490     17200     670
            No Driver Found          690       540      1770     120
            Other                    110       160       130      10
GO-RIDE     Cancelled            1663450   1825540   1900800   79390
            Completed            9745500  10068540  10497760  414660
            No Driver Found       243220    740740    474200   13620
            Other                   3410       410      1380       0
GO-SEND     Cancelled             154620    152720    169270    8550
            Completed             899260   1037320   1124700   46060
            No Driver Found         9860     47790     50900    3610
            Other                    160        10        80       0
GO-SHOP     Cancelled             371510    171110    114150    3770
            Completed             555850    415850    380000   13320
            No Driver Found         1140      7010     18850     200
            Other                    120         0        30       0
GO-TIX      Cancelled               7280      9310      6280     250
            Completed                680      3480      1770      40
            Failed/Timeout           770      1970      1590      40
            Other                      0         0         0       0
grand_total                     17206430  17247120  17601800  681230


month                       grand_total
service     status
GO-BOX      Cancelled           29970.0
            Completed           65030.0
            No Driver Found      3510.0
            Other                   0.0
GO-CLEAN    Cancelled            1740.0
            Completed           14510.0
            No Driver Found       610.0
            Other                 670.0
GO-FOOD     Cancelled         2033930.0
            Completed         6715000.0
            No Driver Found     39260.0
            Other                1670.0
GO-GLAM     Cancelled            1270.0
            Completed            7630.0
            No Driver Found      2060.0
            Other                  40.0
GO-KILAT    Cancelled            1050.0
            Completed           17340.0
            No Driver Found      1380.0
            Other                   0.0
GO-MART     Cancelled           85700.0
            Completed          196430.0
            No Driver Found       410.0
            Other                   0.0
GO-MASSAGE  Cancelled            7330.0
            Completed           42610.0
            No Driver Found      3120.0
            Other                 410.0
GO-RIDE     Cancelled         5469180.0
            Completed        30726460.0
            No Driver Found   1471780.0
            Other                5200.0
GO-SEND     Cancelled          485160.0
            Completed         3107340.0
            No Driver Found    112160.0
            Other                 250.0
GO-SHOP     Cancelled          660540.0
            Completed         1365020.0
            No Driver Found     27200.0
            Other                 150.0
GO-TIX      Cancelled           23120.0
            Completed            5970.0
            Failed/Timeout       4370.0
            Other                   0.0
grand_total                  52736580.0